version: '3'
services:
  sluice:
    build: 
      context: .
      dockerfile: Dockerfile
      #ports:
      #- "8080:8080"
    volumes:
     - .:/code 
  sluicelb:
    image: 'haproxy:latest'
    links:
          - sluice
    ports:
          - "4000:80"
    volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - ./conf/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
