# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import register.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200)),
                ('publicKey', models.TextField(validators=[register.models.validate_ssh_key])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modifyed_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
