# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_microservice_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microservice',
            name='publicKey',
            field=models.TextField(validators=[register.models.validate_ssh_key]),
        ),
    ]
