# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sluiceuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='sluiceuser',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='email address'),
        ),
    ]
