# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 09:55
from __future__ import unicode_literals

from django.db import migrations
import oauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sluiceuser',
            name='token',
            field=oauth.models.JSONField(max_length=254, null=True),
        ),
    ]
